Component/AppointmentClassificationViewComponent.cs
using OnTime.ViewModels;

namespace OnTime.Component
{
    public class AppointmentClassificationViewComponent: ViewComponent
    {
        private readonly IRepositoryClassification _repository;
        public AppointmentClassificationViewComponent(IRepositoryClassification repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke(int appointmentId, string currentClassification)
        {
            return View(new MarkAppointmentClassification
            {
                Classifications = _repository.GetAll().Select(c => c.Name),
                AppointmentId = appointmentId,
                CurrentClassification= currentClassification
            });
        }
    }
}

Component/AppointmentsNavigationViewComponent.cs
using OnTime.Models;

namespace OnTime.Component
{
    public class AppointmentsNavigationViewComponent: ViewComponent
    {
        private readonly IRepositoryClassification _repository;
        public AppointmentsNavigationViewComponent(IRepositoryClassification repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            return View(_repository.GetAll().Select(c => c.Name));
        }
    }
}

Pages/AddAppointment.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnTime.Models;

namespace OnTime.Pages
{
    public class AddAppointmentModel : PageModel
    {
        private readonly IRepositoryAppointment _repository;
        [BindProperty]
        public Appointment CurrentAppointment { get; set; } = new();
        public AddAppointmentModel(IRepositoryAppointment repository)
        {
            _repository = repository;
        }
        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            CurrentAppointment.PostDateTime = DateTime.Now;
            CurrentAppointment.ClassificationId = 1;
            
            if(ModelState.IsValid)
            {
                _repository.AddAppointment(CurrentAppointment);
                return RedirectToRoute(new { Controller = "Home", action = "Index", classification = ClassificationTypes.Awaiting });
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPostRemove(int appointmentId, string urlClassification)
        {
            _repository.RemoveById(appointmentId);
            return RedirectToRoute(new  { Controller = "Home", action = "Index", classification = urlClassification });

        }
    }
}

Views/Shared/AppointmentSummary.cshtml
@model Appointment
@{
    string colorBand = "task__band-grey";
}


@switch (Model?.Classification?.Name)
{
    case "Awaiting":
        colorBand = "task__band-grey";
        break;
    case "Succesfull":
        colorBand = "task__band-green";
        break;
    case "Missed":
        colorBand = "task__band-yellow";
        break;
    case "Canceled":
        colorBand = "task__band-red";
        break;
}
<div class="task-container">
    <div class="task__info-container">
        <div class="post__info">
            <div>
                <span class="task__band-round @colorBand font-secondary">
                    @Model?.Classification?.Name
                </span>
            </div>
            <div>
                <span class="task__info font-secondary">
                    Posted on: @Model?.PostDateTime
                </span>
            </div>
        </div>
        
        <a asp-page="/EditAppointment" asp-route-appointmentId="@Model?.Id" class=" task__edit"><i class="fa-solid fa-pen-to-square"></i></a>
    </div>
    <section class="task__title">
        <h3>Task/appointment on @Model?.AppointmentDateTime</h3>
    </section>
    <section class="task__feature">
        <label for="objective">
            <span class="font-bold">Objective</span>
        </label>
        <p id="objective">@Model?.Objective</p>
    </section>
    <section class="task__feature">
        <label for="reason">
            <span class="font-bold">Reason</span>
        </label>
        <p id="reason">@Model?.Reason</p>
    </section>
    <section class="task__feature">
        <label for="additionalInfo">
            <span class="font-bold">Additional Info</span>
        </label>
        <p id="additionalInfo">@Model?.AdditionalInfo</p>
    </section>
    <div class="task__options">
        <form asp-page="/AddAppointment" asp-page-handler="Remove" method="post">
            <input type="hidden" name="appointmentId" value="@Model?.Id" />
            <input type="hidden" name="urlClassification" value="@Model?.Classification?.Name" />
            <button type="submit" class="btn btn-red deleteButton">Delete</button>
        </form>
        <div class="btn btn-blue drop-button drop-down">
            Mark As
            <div class="drop-down__content">
                <ul class="list drop-down__list">
                    <vc:appointment-classification appointment-id="@Model!.Id" current-classification="@Model?.Classification?.Name"/>
                </ul>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/style/OnTimeStyle.css" rel="stylesheet"/>
     <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <title>OnTime</title>
</head>
<body>
    <header>
        <div class ="nav">
            <h2 class="h1-header">OnTime</h2>
            <vc:appointments-navigation/>
        </div>
    </header>
    <main>
        <div>
            <nav class="nav-links btn-container">
                <a class="btn btn-blue add-btn" asp-page="/AddAppointment">Add Task/Appointment</a>
                <a class="btn btn-red add-btn" asp-controller="History" asp-action="AppointmentsHistory">History</a>
            </nav>
        </div>
        @RenderBody()
    </main>
    <footer>
        <div class="ft-flex font-secondary">
            <div class="ft-grid">
                <div class="ft__containers">
                    <h3 class="ft__item">OnTime</h3>
                    <p>
                        This is an appointment-schedule app and the main goal is to store
                        appointments or tasks into the database and notify you when you have
                        a task or an appointment.
                    </p>
                </div>
                <div class="ft__containers">
                    <h3 class="ft__item">Find this project on</h3>
                    <a class="link-secondary" href="https://github.com/drcipri/OnTime">Github</a>
                    <h3 class="ft__item">Documentation</h3>
                    <a class="link-secondary" href="https://github.com/drcipri/OnTime/blob/main/ReadMe.md">ReadMe.md</a>
                </div>
            </div>
            <div class="ft__bottom">
                <p>2023</p>
            </div>
        </div>
    </footer>
</body>
<script>
    function confirmDelete() {
        var result = confirm("Are you sure ?");
        if (!result) {
            event.preventDefault(); // prevent the default action of the button click event
        }
    }

   var deleteButtons =  document.querySelectorAll(".deleteButton");
    deleteButtons.forEach(function (button) {
        button.addEventListener("click", confirmDelete);
    });
   
</script>
</html>